apiVersion: v1
kind: Service
metadata:
  name: myowncloudappmysql
  labels:
    app: owncloud
spec:
  ports:
  - port: 3306
  selector:
    app: owncloud
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myowncloudappmysql
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
          app: owncloud
          tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-eksrootpassword
              key: ekspassword
        - name: MYSQL_USER
          value: niharika
        - name: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistentvolume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistentvolume
        persistentVolumeClaim:
          claimName: mysql-pvc
