apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
 - name: mysql-password
   literals:
      - password=niharika31
 - name: mysqluser-password
   literals:
      - myuserpassword=niharika28
resources:
   - database_deployment.yml
   - myowncloud_deploymentcode.yml