apiVersion: v1
kind: Service
metadata:
  name: myowncloudapp
  labels:
    app: owncloud
spec:
  ports:
  - port: 80
    nodePort: 30039
  selector:
    app: owncloud
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myowncloud-persistentvolumeclaim
  labels:
    app: owncloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myowncloudapp
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: frontend
    spec:
      containers:
      - image: owncloud:latest
        name: owncloud
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-eksrootpassword
              key: ekspassword
        - name: MYSQL_USER
          value: niharika
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqluser-password
              key: myuserpassword
        - name: MySQL_DATABASE
          value: mysqldatabase
        ports:
        - containerPort: 80
          name: owncloud
        volumeMounts:
        - name: myowncloud-persistentvolumeclaim
          mountPath: /var/www/html
      volumes:
      - name: myowncloud-persistentvolumeclaim
        persistentVolumeClaim:
          claimName: owncloud-pvc